@BlueBellDolls_Server_HostAddress = http://localhost:5297
POST {{BlueBellDolls_Server_HostAddress}}/api/BookingRequests
Content-Type: application/json

{
  "kittenId": 2,
  "customerName": "Иван Иванов (Тест)",
  "customerPhone": "+7 (900) 123-45-75"
}
